### ISSUE TITLE
Dummy placeholder for missing paper > correct count of published papers

### ISSUE THREAD

**Issue by mmunarrizquantum** [quantum-journal/o3po#37]
Definitely not urgent, but would it be possible to introduce a dummy placeholder for the missing paper (or to change the way the number that is shown is calculated by adding +1) so that the final count of published papers on the landing page is correct? It's a small thing, but I would fix it if at all possible.

**Comment by cgogolin** [comment]
The count on the quantum website is correct. We just don't have a paper number 12 (due to technical issues back in the days), so that the page number is always one larger than the number of paper, i.e., the paper with page number 107 is actually the 106th paper that we published. For other journals this will not be an issue.
